name: DefaultConfig
version: v0.1.0
schema:
  tables:
    - name: user
      fields:
        - name: user_id
          type: int
          is_primary_key: true
        - name: name
          type: string
        - name: registered_date
          type: timestamp
          has_default: true
    - name: note
      fields:
        - name: note_id
          type: int
          is_primary_key: true
        - name: note
          type: string
        - name: user_id
          type: int
        - name: created_at
          type: timestamp
          has_default: true
